version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install
      - npm install -g @aws-amplify/cli
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Build completed on `date`"
      - amplify configure --app-id d3cbd7vrlkxvqm -y
      - amplify publish -y
      # Or alternatively if you only want to trigger the deployment:
      # - aws amplify start-job --app-id d3cbd7vrlkxvqm --branch-name main --job-type RELEASE

artifacts:
  files:
    - '**/*'
  base-directory: .next