version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Build completed on `date`"
      # Use the AWS CLI directly to trigger a deployment
      - aws amplify start-job --app-id d3cbd7vrlkxvqm --branch-name main --job-type RELEASE

artifacts:
  files:
    - '**/*'
  base-directory: .next